---
version: 2.1
orbs:
  android: circleci/android@1.0.3
jobs:
  build-and-test:
    docker:
      - image: cimg/android:2023.07
    resource_class: large
    steps:
      - checkout
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - android/run-tests:
          test-command: ./gradlew lint testDebug --continue
      # - android/start-emulator-and-run-tests:
      #     test-command: ./gradlew connectedDebugAndroidTest
      #     system-image: system-images;android-25;google_apis;x86
      - run:
          name: Assemble release build
          command: |
            ./gradlew assembleRelease
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: |
            docker build -t maniyarpawan/circlecicddocker .
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push maniyarpawan/circlecicddocker
workflows:
  sample:
    jobs:
      - build-and-test
